name: data
on:
  schedule:
    - cron: 59 23 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://datos.madrid.es/egob/catalogo/300461-1-papeleras.csv
          downloaded_filename: new_data.csv
          postprocess: ./postprocess.ts
